global:
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
    - OpenMetricsText1.0.0
    - OpenMetricsText0.0.1
    - PrometheusText1.0.0
    - PrometheusText0.0.4
  evaluation_interval: 15s
  metric_name_validation_scheme: utf8
runtime:
  gogc: 75
alerting:
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: []
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    track_timestamps_staleness: false
    scrape_interval: 15s
    scrape_timeout: 10s
    scrape_protocols:
      - OpenMetricsText1.0.0
      - OpenMetricsText0.0.1
      - PrometheusText1.0.0
      - PrometheusText0.0.4
    always_scrape_classic_histograms: false
    convert_classic_histograms_to_nhcb: false
    metrics_path: /metrics
    scheme: http
    enable_compression: true
    metric_name_validation_scheme: utf8
    metric_name_escaping_scheme: allow-utf-8
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - localhost:9090
        labels:
          app: prometheus

  - job_name: one-stop
    honor_timestamps: true
    track_timestamps_staleness: false
    scrape_interval: 15s
    scrape_timeout: 10s
    scrape_protocols:
      - OpenMetricsText1.0.0
      - OpenMetricsText0.0.1
      - PrometheusText1.0.0
      - PrometheusText0.0.4
    always_scrape_classic_histograms: false
    convert_classic_histograms_to_nhcb: false
    metrics_path: /management/metrics
    scheme: http
    enable_compression: true
    metric_name_validation_scheme: utf8
    metric_name_escaping_scheme: allow-utf-8
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - audit-service:9002
          - notification-service:9002
          - rail-service:9002
          - share-service:9002
          - user-service:9002

otlp:
  translation_strategy: UnderscoreEscapingWithSuffixes
