# This workflow will build a Java project with Maven, and cache/restore
# any dependencies to improve the workflow execution time
# For more information
# see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Build and Deploy Native Modulith ARM

# to login to the github container repo use:
#    docker login https://ghcr.io -u phillwatson -p <personal-access-token>
# where:
#  <personal-access-token> is created here https://github.com/settings/tokens
# This will create an auth entry in the ~/.docker/config.json/

on:
  workflow_dispatch:
    inputs:
      revision:
        description: 'Build revision'
        required: true
        default: '1.0.0'

env:
  REGISTRY: ghcr.io
  QUARKUS_CONTAINER_IMAGE_REGISTRY: ghcr.io
  QUARKUS_CONTAINER_IMAGE_GROUP: ${{ github.repository_owner }}
  QUARKUS_CONTAINER_IMAGE_PUSH: true

jobs:
  build:
    name: package and deploy
    runs-on: ubuntu-22.04-arm
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout the code
      uses: actions/checkout@v5
#      with:
#        ref: modulith

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: 'maven'

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven
      # skips the tests due to lack of "test" profile
      run: |
        mvn -B deploy -Pclient -Dnative -Drevision=${{ github.event.inputs.revision }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}

    - name: Build and push Client Docker image
      uses: docker/build-push-action@v6
      with:
        context: client/
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/client:${{ github.event.inputs.revision }}
        labels: ${{ steps.meta.outputs.labels }}
